version: "3.9"
   
services:
  web:
    build: .
    command: python main.py 80
    volumes:
      - .:/code
    container_name: weatherapp-container
    networks:
      - default
      - postgres
    restart: always

networks:
  default:
    name: weather_app_default
    internal: true
  postgres:
    name: postgres_default
    external: true
