version: "3.9"
   
services:
  db:
    image: postgres:latest
    volumes:
      - ./data/db:/var/lib/postgresql/db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgresdb-container
    user: postgres
  web:
    image: weather-app:latest      #    build: .
    command: python main.py 80
    volumes:
      - .:/code
    ports:
      - "80"
    container_name: weatherapp-container
    depends_on:
      - db
